### ISSUE TITLE
Eloquent driver pagination

### ISSUE THREAD

**Issue by vasil-atanasov** [flat3/lodata#118]
Eloquent driver pagination ($skip) stops working due to changes in commit: https://github.com/flat3/lodata/commit/c1d688369f74bd13d70d6f5690b645f79deed8f6

src/Drivers/EloquentEntitySet.php
In the query() method `$builder->getModels()` is changed with `$builder->lazy()`. It seems that new Laravel lazy() method cannot paginate and the $skip parameter is ignored. You always get the first $top (ex. 20) rows. 

From the Laravel docs 
Once again, if you plan to update the retrieved records while iterating over them, it is best to use the lazyById method instead. This method will **automatically paginate the results** based on the record's primary key.

**Comment by 27pchrisl** [comment]
Thanks @vasil-atanasov! I had not included top/skip in the Eloquent driver tests. This is now resolved and the bug fixed using `lazyById` as you suggested. Thanks for the report!
