### ISSUE TITLE
@context should be @odata.context where i could set that

### ISSUE THREAD

**Issue by Hessuss** [flat3/lodata#121]
Hi, like in topic. By the :
http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793054
@context should be @odata.context where i could set that?
Please help.

**Comment by 27pchrisl** [comment]
Hi @Hessuss, Lodata defaults to OData 4.01 and that version of the spec dropped the "odata." prefix (https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_ControlInformation).

However, if you set your client's `odata-version` HTTP header to `4.0` you'll get the 4.0 behaviour.
