### ISSUE TITLE
Pulling data from SQL views

### ISSUE THREAD

**Issue by onthefocus** [flat3/lodata#132]
Would it be possible to extend the package to process SQL views, not only the tables? We are using postgres and there is no possibility to set identifier field for view.

**Comment by vasil-atanasov** [comment]
What do you mean by ‘_there is no possibility to set identifier field for view._’

Haven’t tried with Postgres, but i’m successfully using the package with MySql views.

**Comment by onthefocus** [comment]
**What we want to do**

In our system we have many PostgreSQL tables and view, which using lodata package we would like to pass their data to PowerBI in OData format.

**Current Issue**

To solve our challenge we installed lodata package and some DB tables and views are registered (in LodataServiceProvider -> boot() method) to be outputted as OData. For that we use \Flat3\Lodata\Drivers\SQLEntitySet driver. 

Here we defined tables which should be outputted, all good with DB tables, but if there is a DB view it fails due to missing primary key: 

trait SQLSchema -> function discoverProperties() -> if (!$type->getKey()) {
            throw new InternalServerErrorException

DB views in PostgreSQL can't have primary keys.

**So Question/Problem**

How to pass DB views to the lodata package and consume them via OData standard in PowerBI? 

**Our Restrictions**

We have situation that there are many our product customers and we can't do hardcoding as different our product custoers might have different DB views, which we just want to pass to the PowerBI. 
As alternative to use just json connection in Power BI does not works, that each client has a dozen views, where you can't import each one-by-one (too much time consuming), so OData standard is the best choice.

P.S. Would be very much appreciated with any form of your help here!

**Comment by vasil-atanasov** [comment]
Try this

```
$type = new \Flat3\Lodata\EntityType('ViewNameType');

// Define your key here. If you have an id column in your view use that
// If not pick another column from the view that has unique values.
// Set the Type according to the picked column for key. 
// If your id is int, int64 is fine. If for example your are using uuid's than use string. 
$type->addDeclaredProperty('id', \Flat3\Lodata\Type::int64());

// After you declare the property, finally set it as key. 
// You was missing this step, that't why you got missing_primary_key error
$type->setKey($type->getProperty('id'));

$viewNameSet = \Flat3\Lodata\Drivers\SQLEntitySet::factory('ViewName', $type)
   ->setTable('your_db_view_name')
   ->discoverProperties();

 Lodata::add($viewNameSet);
```

**Comment by 27pchrisl** [comment]
Hi @onthefocus,

I have released https://github.com/flat3/lodata/releases/tag/v2.1.5 to remove the constraint with discovery and solve the issue you found. It was guarding against keyless types, however Lodata works fine with keyless types if you're performing an operation like a query.

There's a small issue in this configuration that the metadata still advertises that the entity set supports create/update/delete when it actually doesn't, but I will resolve this in a future version. It shouldn't cause the client a problem if it doesn't try and perform those actions.

Appreciate your taking the time to create a workaround @vasil-atanasov - this would have been a good solution if more areas of the project had relied on a type key.

**Comment by onthefocus** [comment]
> Try this
> 
> ```
> $type = new \Flat3\Lodata\EntityType('ViewNameType');
> 
> // Define your key here. If you have an id column in your view use that
> // If not pick another column from the view that has unique values.
> // Set the Type according to the picked column for key. 
> // If your id is int, int64 is fine. If for example your are using uuid's than use string. 
> $type->addDeclaredProperty('id', \Flat3\Lodata\Type::int64());
> 
> // After you declare the property, finally set it as key. 
> // You was missing this step, that't why you got missing_primary_key error
> $type->setKey($type->getProperty('id'));
> 
> $viewNameSet = \Flat3\Lodata\Drivers\SQLEntitySet::factory('ViewName', $type)
>    ->setTable('your_db_view_name')
>    ->discoverProperties();
> 
>  Lodata::add($viewNameSet);
> ```

@vasil-atanasov assuming that our id is an uuid (string) what would be \Flat3\Lodata\Type ?

**Comment by onthefocus** [comment]
Thank you guys. You support is awesome ! Keep going in the same pace.

You have a really good product/package, and good luck with its future improvements! We are going to use it definitely in our live environments and might come back to you with some questions.
