### ISSUE TITLE
Case sensitive column name is not supported

### ISSUE THREAD

**Issue by merouanekhalili** [flat3/lodata#136]
Hi,

I have a PostgresSQL database with case sensitive column names, when I try a query discovery I got the below exception :

ErrorException 

  Undefined array key "MY_COLUMN_NAME"

  at C:\Me\www\data-api\vendor\flat3\lodata\src\Drivers\SQL\SQLSchema.php:45
     41▕             }
     42▕
     43▕             var_dump($columns);
     44▕
  ➜  45▕             $column = $columns[$index->getColumns()[0]];
     46▕             $key = $this->columnToDeclaredProperty($column);
     47▕
     48▕             if ($column->getAutoincrement()) {
     49▕                 $key->addAnnotation(new Computed());

  1   vendor\flat3\lodata\src\Drivers\SQL\SQLSchema.php:45
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()

  2   app\Providers\AppServiceProvider.php:29
      Flat3\Lodata\Drivers\SQLEntitySet::discoverProperties()

**Comment by 27pchrisl** [comment]
Thanks for the report @merouanekhalili, looks like I was getting tripped up by https://github.com/doctrine/dbal/blob/10df50f949c78c1f3666451470183ca01c4c4fa5/src/Schema/AbstractSchemaManager.php#L891 making the names lower case in the associative array. I have fixed this by not relying on that key being the correct name.

**Comment by 27pchrisl** [comment]
I have released https://github.com/flat3/lodata/releases/tag/v3.0.2 with this change. Please re-open this issue if the problem is not solved for you.

**Comment by merouanekhalili** [comment]
Hi Chris,

Thanks for your help.

The new release fix only the discovery step, but when you try to get the data the generated SQL statment is not correct.
I got the below error :

{"@context":"http://127.0.0.1:8000/odata/$metadata#cities","value":[OData-error: {"code":"query_error","message":"The executed query returned an error: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"`\"\nLINE 1: SELECT dimensions.\"DIM_CITIES\".`ID` AS ID, dimensions.\"DIM_C...\n                                       ^","target":null,"details":[],"innererror":{}}


Below the code to test :

**dimensions."DIM_CITIES" definition**

CREATE TABLE dimensions."DIM_CITIES" (
	"ID" int4 NOT NULL,
	"NAME" varchar NULL,
	"LATITUDE" float4 NULL,
	"LONGTITUDE" float4 NULL,
	CONSTRAINT cities_pkey PRIMARY KEY ("ID")
);

**app\Providers\AppServiceProvider.php**


<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        $cityType = \Flat3\Lodata\EntityType::factory('city');
        $cityType->addDeclaredProperty('ID', \Flat3\Lodata\Type::int64());
        $cityType->addDeclaredProperty('NAME', \Flat3\Lodata\Type::string());
        $cityType->addDeclaredProperty('LATITUDE', \Flat3\Lodata\Type::double());
        $cityType->addDeclaredProperty('LONGTITUDE', \Flat3\Lodata\Type::double());
        $citySet = \Flat3\Lodata\Drivers\SQLEntitySet::factory('cities', $cityType)
            ->setTable('dimensions."DIM_CITIES"')
            ->discoverProperties();
        \Flat3\Lodata\Facades\Lodata::add($citySet);
    }
}

**Comment by 27pchrisl** [comment]
Thanks for the repro code @merouanekhalili, I've released https://github.com/flat3/lodata/releases/tag/v3.0.4 with additional fixes and test cases for these issues.

**Comment by merouanekhalili** [comment]
The issue is fixed, thanks Chris for your help.
