### ISSUE TITLE
Syntax error: 7 ERROR:  syntax error at or near "`

### ISSUE THREAD

**Issue by poskusmin** [flat3/lodata#152]
```
Flat3\Lodata\Exception\Protocol\InternalServerErrorException {#2343
  #httpCode: 500
  #odataCode: "query_error"
  #message: """
    The executed query returned an error: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
    LINE 1: SELECT passengers.`id` AS id, passengers.`number` AS number,...
                              ^
    """
```
    

Currently having this error when creating a PostgreSQL View from real table.

Lodata boot:
    
```
    $type = new EntityType('passenger');

    $type->addDeclaredProperty($key, Type::string());
    
    $property = $type->getProperty($key);
    
    $type->setKey($property);
    
    $set = (new SQLEntitySet('passengers', $type))
        ->setTable('passengers')
        ->discoverProperties();
        
    Lodata::add($set);
```

Overall simple tables with integers and strings works fine, but when JSON, relationships are in the table - throws errors which are pretty much hard to understand why.

**Comment by 27pchrisl** [comment]
Hi @poskusmin, could you first let me know which version of Lodata you're using? 4.0.0 was released yesterday and I want to check that's not caused this regression.

The issue appears to be that Lodata is using the wrong identifier quoting style for your database, it should be using `"` characters for postgres, but it's using ` characters for mysql instead. It should detect the right style by checking which PDO driver is in use.

Could you add to your code:

```php
dd($set->getDriver());
```

to get Laravel to show the PDO driver type it thinks it is supposed to be using for your database?

**Comment by 27pchrisl** [comment]
Cool, thanks!
