### ISSUE TITLE
EloquentEntitySet::Discover does not respect a Model's connection preference.

### ISSUE THREAD

**Issue by gflynn-ppro** [flat3/lodata#153]
Great work. I've noticed that with 3.x and 4.x that if I do discovery on an eloquent model that uses a different connection than the default, it will fail to discover appropriately. 

The use case here is leveraging both MySQL and Postgres databases to power the same application, and setting "connection" on the model to the appropriate connection. See: https://laravel.com/docs/8.x/eloquent#database-connections 

The fix seems to be setting the connection name in: \Flat3\Lodata\Drivers\EloquentEntitySet::__construct

`$this->setConnectionName($this->getModel()->getConnectionName() ?: DB::getDefaultConnection());`

**Comment by 27pchrisl** [comment]
Hi @gflynn-ppro, agree that your assessment makes sense. I think it might be better to override `getConnection` in `EloquentEntitySet` as:

```php
    public function getConnection(): ConnectionInterface
    {
        return $this->getModel()->getConnection();
    }
```

so that the returned connection is always provided from the model, including if the model was updated in some way at runtime?

**Comment by 27pchrisl** [comment]
In fact that would make it consistent with the override of `getTable`, so I think that makes sense

**Comment by 27pchrisl** [comment]
This should be resolved in https://github.com/flat3/lodata/releases/tag/v4.0.1

**Comment by gflynn-ppro** [comment]
It seems to work perfectly. Keep up the great and diligent work.
