### ISSUE TITLE
Lodata not respecting nullable property when inserting data

### ISSUE THREAD

**Issue by ianket** [flat3/lodata#157]
When I send a POST request for creating a model that has an attribute which is marked as non-nullable it still proceeds and ends up trying to insert the data in the database with without a value for the non-nullable field, which ends up giving an SQL error. Below is an example of the request. Perhaps I need to specify on a secondary place that an attribute is required, but I wasn't able to find how to do this if so.

I am using version 4.0.1 of Lodata. 

A smaller secondary remark that I have, is that in my instance I would prefer when a InternalServerErrorException would be thrown by the Transaction that it would actually throw the exception instead of creating a response of it directly. This way I also can prevent from the given error messages to be too crude (and perhaps too informative) for the end user. 

![image](https://user-images.githubusercontent.com/12576303/148065457-c9fbca45-3772-4e5e-9dba-17851022e59f.png)

Thanks in advance for the reply!

**Comment by 27pchrisl** [comment]
Thanks for the issue @ianket, I'm looking into it. Properties should be being marked not nullable by default if you're using the Eloquent model discovery technique (should come through in the metadata). However as you point out, that's not actually being propertly checked for Create requests (or Update requests on the entity if you try and set a property to null, or updates / deletes on entity primitives).

I'll also take a look at rethrowing those exceptions too.

**Comment by ianket** [comment]
Thanks for the response @27pchrisl! The properties are indeed marked non-nullable by default according to the info data returned. Looking forward for the change, thank you!

**Comment by 27pchrisl** [comment]
@ianket I still have to write more tests to verify every variant of nullable/computed/default values, but you may be able to verify for me that version `5.x-dev` handles this correctly for your test case, and now does rethrow exceptions that occur during the transaction.

**Comment by 27pchrisl** [comment]
I think 5.0 is good to go so I have released it https://github.com/flat3/lodata/releases/tag/v5.0.0
But I'll leave this open until it's verified fixed this issue.

**Comment by ianket** [comment]
Thansk @27pchrisl! I'll let you know tomorrow if it fixed the issue!

**Comment by ianket** [comment]
I checked it and it's indeed fixed! Thank you @27pchrisl! I also verified that I can capture the exceptions now, thank you!
