### ISSUE TITLE
Store discovery data result to prevent mapping each request

### ISSUE THREAD

**Issue by ianket** [flat3/lodata#169]
I've hit a small speed issue when using lodata with a database containing >20 tables with alot of MySQL Keys. When running it adds a flat ~8s to each request, coming from doing all discover functionality in the Service Provider, which is quite an annoyance when you are fetching data from a table that has just 10 rows. 

Given this issue I was wondering if it is possible to make it so that lodata has the ability to store the result of the discovery on file and also the ability to read this file again. This so that it doesn't have to do the discovery each and every request. 

I was able to get this functionality working by myself by quickly adding a setter & getter for the `ObjectArray $model` variable in `Flat3\Lodata\Model` (and adding it to the facade). And then doing the following in my in ServiceProvider:

```php
// LodataModelServiceProvider

if (Storage::exists("lodata.serialized")) {
    Lodata::setModel(unserialize(Storage::get("lodata.serialized")));
} else {

    // Execute all model discovery here...

    $serialized = serialize(Lodata::getModel());
    Storage::put("lodata.serialized", $serialized);
}
```

_(The problem with this code is that it doesn't discover again once the data is set, but just as an example)_

My question is if it is possible to have this functionality natively supported in Lodata. Even the functionality to get and set the `ObjectArray $model` would be enough for me, and then having the responsibility of storing, reading and serialization on the project itself.

Thanks in advance!

**Comment by ianket** [comment]
Alright Thanks! Most of the time goes to each INFORMATION_SCHEMA.KEY_COLUMN_USAGE query fetching the keys from each and every table every request, which takes about ~0.5s per query on our production server. I expect that smaller servers tend to have quite a bit faster responsetime.

If you need any details, feel free to let me know!

**Comment by 27pchrisl** [comment]
Hi, this functionality introduced in https://github.com/flat3/lodata/releases/tag/v5.0.1 - let me know if the new config options work for your use case https://github.com/flat3/lodata/blob/f1d8e0d1da054e5e31303a0d86a89c1c1c6dc94c/config.php#L59

**Comment by ianket** [comment]
It does seem to work yes, only i noticed that having the ttl at 0 does mean it _won't_ be stored at all. I guess it should be `->rememberForever(...)` when ttl is 0. But after setting it to something above 0 it does seem to work.

Thanks that you use the Laravel Cache functionality, I also have the ability to create my own functionality that has the ability to check for database changes in the background, and if so deletes the cache key and re-do the discovery without it having to influence the end-user. 

Thanks!

**Comment by 27pchrisl** [comment]
Hi, a null value should store forever (same as rememberForever). My aim for lodata is to make it as developer friendly out of the box as possible, which is why the default value is 0 to prevent caching while you're playing around with discovery!

**Comment by ianket** [comment]
Oops, I've seemed to misread it, my bad! null does work indeed, thank you!
