### ISSUE TITLE
Loading Expanded Model from Expanded Model

### ISSUE THREAD

**Issue by rocketescom** [flat3/lodata#183]
I am not sure if this is possible within that library, but can i use an Expanded Query on and Expanded Objekt?

For Example:

Clients -> Locations -> Countries

Each Client as Multiple Locations, and Each Location has Multiple Country Objects. When ill know try with this query:

http://localhost/api/Clients/query?$expand=locations($expand=country)

Then it seems the nested Expand is not working (but as i understand the oData Library this should work)

Is there a way to handle this within the lodata library?

Thanks in advance

**Comment by 27pchrisl** [comment]
Hi,

Yes this should work, I checked and there is a test for it.

https://github.com/flat3/lodata/blob/eae9e2823a6fa05fa487f062a3cc74d41b6fd4c1/tests/Navigation/NavigationTest.php#L265
resulting in
https://github.com/flat3/lodata/blob/5.x/tests/Navigation/__snapshots__/EloquentTest__test_expand_hasmany_entity_expand_full_metadata__1.json

The test performs a request for `http://localhost/odata/flights?$expand=passengers($expand=flight)` which is very similar to what you're testing. Your example said Locations -> Countries - should the second expansion be for the `countries` property? If you're using the Eloquent entity set it'll be looking for a function on the model with that name.

**Comment by 27pchrisl** [comment]
Closing this one, please re-open if this issue persists.
