### ISSUE TITLE
Composer issue with Laravel 9

### ISSUE THREAD

**Issue by ianket** [flat3/lodata#190]
Laravel 9 has some changes with illuminate/events requiring version 9. But the current 5.2 version of Lodata still requires version 8. I'm not certain if this brings any breaking changes, but as for now Lodata does not work with Laravel 9.

```
  Problem 1
    - illuminate/events[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.1) does not satisfy that requirement.
    - Only one of these can be installed: illuminate/events[v8.0.0, ..., 8.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/events and thus cannot coexist with it.
    - flat3/lodata[v5.2.0, ..., 5.x-dev] require illuminate/events ^8.0 -> satisfiable by illuminate/events[v8.0.0, ..., 8.x-dev].
    - Root composer.json requires flat3/lodata ^5.2 -> satisfiable by flat3/lodata[v5.2.0, 5.x-dev].
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].
```

**Comment by 27pchrisl** [comment]
Hi, yes at the moment I can't update the dependencies to include v9, as the Flysystem update is causing issues. I need to make several changes in Lodata to work with the new Flysystem API in the next few days.

**Comment by ianket** [comment]
Alright, that's fine! Looking forward for the patch!

**Comment by 27pchrisl** [comment]
Now resolved in https://github.com/flat3/lodata/releases/tag/v5.3.0

**Comment by ianket** [comment]
It indeed seems to work now. Thanks @27pchrisl!
