### ISSUE TITLE
Array to string conversion on Collection toEtag

### ISSUE THREAD

**Issue by Iseldore** [flat3/lodata#204]
Hi, I'm sorry to came up with another issue 😕 

I have a DeclaredProperty of type Collection. When I do `odata/Offers` all is good. But when I do `odata/Offers(1)` I have the following error `Array to string conversion`. This exception is thrown in file `Primitive.php` on line 98 (`return null === $value ? null : (string) $value;`). This exception makes sense because `$value` is an array.

When I comment out these lines in `ComplexValue.php` on (382-384), all is good : 
```
if ($value instanceof ETagInterface) {
    $input[$property->getName()] = $value->toEtag();
}
```
Is this a bug or I'm doing something wrong ?

Thanks again

**Comment by 27pchrisl** [comment]
No this looks like a bug, is this a JSON property of an Eloquent model or something like that?

**Comment by Iseldore** [comment]
Yes, this is a custom attribute on my Eloquent model : 
```
use Flat3\Lodata\Type;
use Flat3\Lodata\Type\Collection;
class Offer extends Model {
    ...
    public function getLargePicturesAttribute() {
        $count = 4;
        $c = new Collection();
        for($i = 0; $i < $count; $i++)
            $c->add(new Type\String_('https://picsum.photos/200'));
        return $c;
    }
}
```
and declaration : 
```
$entity = \Lodata::getEntityType('Offer');
$entity->addDeclaredProperty('largePictures', Type::collection());
```

**Comment by 27pchrisl** [comment]
I've revamped support for collections in https://github.com/flat3/lodata/releases/tag/v5.6.0. In addition to actually working correctly, the syntax has simplified. Your example could now be written as:

```
use Flat3\Lodata\Type;
use Flat3\Lodata\Type\Collection;
class Offer extends Model {
    ...
    public function getLargePicturesAttribute() {
        $count = 4;
        $c = new Collection();
        for($i = 0; $i < $count; $i++)
            $c[] = 'https://picsum.photos/200';
        return $c;
    }
}
```
and declaration : 
```
$entity = \Lodata::getEntityType('Offer');
$entity->addDeclaredProperty('largePictures', Type::collection(Type::string()));
```

**Comment by Iseldore** [comment]
Thanks, it works !
