### ISSUE TITLE
Pass original exception when uncaptured exception occurs on Transaction execute

### ISSUE THREAD

**Issue by ianket** [flat3/lodata#221]
Whenever a Transaction gets executed, and the source throws an uncaptured exception, it gets pretty tough figuring out the original exception because it does not contain the "previous" exception, only the message.

I think it would be a decent addition that the InternalServerErrorException that gets thrown at Flat3\Lodata\Controller\Transaction.php:1271 gets the original exception passed along so that the error handling can check the details of this error if needed.

**Comment by 27pchrisl** [comment]
Hi Ian, so you're asking to be able to do:

```php
} catch (ProtocolException $e) {
  $originalException = $e->getOriginalException();
}
```

and then be able to evaluate the exception that caused the error?

**Comment by ianket** [comment]
Not entirely I think
At the following:
```php
        } catch (Exception $e) { // Uncaptured errors
            $this->rollback();
            throw new InternalServerErrorException('unknown_error', $e->getMessage());
        }
```

When I use Operator functions via Repositories, exceptions that get thrown within the function always end up here, but because of this I'm unable to find out the exception source correctly.

**Comment by 27pchrisl** [comment]
I've added something that might work in a branch, here is the test:
https://github.com/flat3/lodata/blob/original-exception/tests/Protocol/ErrorReportingTest.php#L92

So if you can capture either the `Response` or the `Exception` in your code, you should be able to navigate to the original exception from there - does this work?

**Comment by ianket** [comment]
Looks perfect yeah! With this I'd be indeed able to get the original exception

**Comment by 27pchrisl** [comment]
Published this in https://github.com/flat3/lodata/releases/tag/v5.9.0

**Comment by ianket** [comment]
Seems to work perfectly. Thank you @27pchrisl !
