### ISSUE TITLE
lodata is only odata 4.01 but devextreme version 4.0 only 

### ISSUE THREAD

**Issue by tamasberei** [flat3/lodata#227]
It seems currently I cannot use with laravel lodata the devextreme because, the devextreme is 4.0 compatible, and the lodata is 4.01. (response contains @odata.count and in the 4.01 the "odata." was removed. Should be a configuration switch to keep compatibility mode 4.0 . So currently the devextreme odatastore not working.

**Comment by 27pchrisl** [comment]
Hi @tamasberei,

You can force the accepted OData version client-side using a header as described here: https://js.devexpress.com/Documentation/ApiReference/Data_Layer/ODataContext/Configuration/

This I think should work:
```js
var context = new DevExpress.data.ODataContext({
    url: "http://localhost:3000/odata/Users",
    beforeSend: function (e) {  
        e.headers = {
            "odata-version": "4.0"
        };
    }
});
```

**Comment by tamasberei** [comment]
Hi,

Your solution solved the problem, thanks!
I also contacted the devexpress, they will consider to 
develop the 4.01 compatibility as well in the ear future.

BR
Tamas Berei

**Comment by 27pchrisl** [comment]
Great!
