### ISSUE TITLE
$count for navigation collection is not correct

### ISSUE THREAD

**Issue by Angelinsky7** [flat3/lodata#254]
**Context**
```php

class Person {
  #[LodataRelationship]
    public function tags(){
        return $this->belongsToMany(Tag::class);
    }
}

class Tag {
}
```

**Db**
```
Table person{id}
Table tags{id}
Table person_tag{person_id,tag_id}
```

**Request**
`http://localhost:8080/odata/Person/1/tags/$count`

**Result**
The total of all tags in the db: The same as if the request was : `http://localhost:8080/odata/tags/$count`
```SQL
SELECT COUNT(*) FROM tags
```

**Expected result**
The query should be the count of all tags of the selected person. Not all the tags.
```SQL
SELECT COUNT(*) FROM tags t JOIN person_tag pt ON pt.tag_id = t.id WHERE pt.person_id = ?;
```
But of course the laravel builder can already do that by it self using the queryBuilder.

**Version**
`"flat3/lodata": "^5.11"`

**Comment by 27pchrisl** [comment]
Hi @Angelinsky7, thanks for the detailed issue report! I believe this should be fixed in the 5.x branch, could you install `flat3/lodata:5.x-dev` and see if this issue is fixed?

**Comment by 27pchrisl** [comment]
Resolved in https://github.com/flat3/lodata/releases/tag/v5.14.0

**Comment by Angelinsky7** [comment]
@27pchrisl thanks a lot for all the patches. 
I'm really sorry for the late answers but I was not around there for all this time.
I'll check everything and if you want maybe create some unit test...
thanks again !

**Comment by 27pchrisl** [comment]
@Angelinsky7 No problem! If any of the issues persist feel free to Reopen the ticket.
