### ISSUE TITLE
HasOne and belongsTo should have the same meaning

### ISSUE THREAD

**Issue by Angelinsky7** [flat3/lodata#259]
**Context**
If we use relationship we should be able to use `hasOne` and `belongsTo` and have the same result.

```php

class Person {

  #[LodataRelationship]
    public function link()
    {
        //Those two statement should have the same behavior....
        return $this->belongsTo(Link::class, 'link_id', 'id' );
        return $this->hasOne(Link::class, ,'id', 'link_id' );
    }
}

class Link {
}
```

**Db**
```
Table person{id, link_id}
Table link{id}
```

**Result**
When getting constraints information about a navigation property, if the navigation property is not describe as `HasOne` or `HasOneOrMany` there is no information about the relationship.

https://github.com/flat3/lodata/blob/7f9ce1ce1c705b29d3959c2932ec5e7efa8c2218/src/Drivers/EloquentEntitySet.php#L418-L435

**Expected result**
We should be able to get information about the relationship either if we use `HasOne` or `BelongsTo` as stated in https://laravel.com/docs/9.x/eloquent-relationships#one-to-one-defining-the-inverse-of-the-relationship

**Version**
`"flat3/lodata": "^5.11"`

**Comment by 27pchrisl** [comment]
BelongsTo relationships are now added as `ReferentialConstraint` entries

**Comment by 27pchrisl** [comment]
Resolved in https://github.com/flat3/lodata/releases/tag/v5.14.0
