### ISSUE TITLE
Error when the columns name contains a dot

### ISSUE THREAD

**Issue by deepcube-srl** [flat3/lodata#270]
When I define an SqlEntitySet with a table having dots in the column name, I have the following error calling the API:
```
{"error":{"code":"invalid_name","message":"The provided name was invalid: Account__r.ExtId__c","target":null,"details":[],"innererror":{}}}
```
If I change the column name and don't use dots, it works.
The code is the following:
```
$segmentsType = new \Flat3\Lodata\EntityType('Object');
        $segmentsSet = (new \Flat3\Lodata\Drivers\SQLEntitySet('Object', $segmentsType))
            -> setTable('table')
            -> discoverProperties();
        \Lodata::add($segmentsSet);
```
I'm using MariaDb 10.5.12 and PHP 7.4.28
Thanks in advance

**Comment by 27pchrisl** [comment]
Hi @deepcube-srl

Yup I can reproduce this issue. The problem is that OData property names can't have dots in them. I think the logical thing in autodiscovery would be to name your property `Account__r_ExtId__c` ?

**Comment by 27pchrisl** [comment]
I created a branch 'dots' with a modification that does this. Could you `composer require flat3/lodata:dev-dots` and see if that resolves things?

**Comment by deepcube-srl** [comment]
I tried and it works removing the dots.
The problem is that we cannot change the table that we must expose and it contains dots in the name.
But if the dot cannot be part of the name, I think that there are no other solutions that the one you proposed...
Thank you very much!

**Comment by 27pchrisl** [comment]
Yup that's fine, no need to change the table name. The next release will include this modification.

**Comment by deepcube-srl** [comment]
I'm sorry, it was wrong: 
_The problem is that we cannot change the table that we must expose and it contains dots in the COLUMNS name.
But if the dot cannot be part of the COLUMNS name, I think that there are no other solutions that the one you proposed..._
Thanks!
