### ISSUE TITLE
Sort by a property in an expanded relationship

### ISSUE THREAD

**Issue by CalamarMihai** [flat3/lodata#286]
Hi, 

Can you help me please find a solution to the following problem:

With this request **http://localhost/api/odata/Customers?$top=10&$expand=city($select=id,name)** I have the following result:

`{
"@context": "http://localhost/api/odata/$metadata#Customers(name,county(),city())",
"value": [
{
"name": "Sallie Maggio DVM",
"county": {
"id": 25,
"name": "Braila",
"code": "BR"
},
"city": {
"id": 3214,
"county_id": 25,
"name": "Chioibasesti"
}
},
{
"name": "Winona Gottlieb",
"county": {
"id": 12,
"name": "Olt",
"code": "OT"
},
"city": {
"id": 8547,
"county_id": 12,
"name": "Rescuta"
}
}
],
"@nextLink": "http://localhost/api/odata/Customers?%24expand=county%2Ccity&select=name&top=2&skip=2"
}`

When I try to sort the result by a child (expand property), I get the error: 

`The orderby parameter specified properties (city.name) that did not exist`

Request: **http://localhost/api/odata/Customers?$top=10&$expand=city($select=id,name)&$orderby=city.name%20desc**

What can I do?

Thank you very much for your help!
Have a nice day!

**Comment by 27pchrisl** [comment]
Hi @CalamarMihai, does `http://localhost/api/odata/Customers?$top=10&$expand=city($select=id,name;$orderby=name%20desc)` work?

**Comment by CalamarMihai** [comment]
@27pchrisl, unfortunately it doesn't work. I guess that's how the collection is sorted if the relationship returns a list. 

I have the same problem when I want to filter depending on the relationship.

**Comment by 27pchrisl** [comment]
Hi @CalamarMihai, were you expecting it to sort the outer items, or the expanded items? It should certainly sort the expanded items. If you're expecting it to sort the outer items I wasn't aware of this syntax - is this something in the OData specification?

**Comment by CalamarMihai** [comment]
I want to sort and filter my customer table by city name. How can I do that?

**Comment by 27pchrisl** [comment]
If you want to filter by city name, you might be able to do that with a lambda expression, something like this:

`http://localhost/api/odata/Customers?$top=10&$expand=city($select=id,name)&$filter=city/any(d:d/name eq 'London')`
