### ISSUE TITLE
Return only allowed data

### ISSUE THREAD

**Issue by marciotheis** [flat3/lodata#288]
Hi!

Has a way to intercept a response or even add a subquery in a request?
Because in some cases, it's necessary to restrict data return identifying the user in jwt.

Thanks !

**Comment by 27pchrisl** [comment]
Hi, depending on how fine-grained you want the control you could do this with Laravel Gates, or by subclassing EloquentEntitySet. Details here: https://lodata.io/getting-started/authorization.html

When doing this, you can still use discovery on custom entity sets using `(new MyEloquentEntitySet(Product::class))->discover()`

**Comment by marciotheis** [comment]
Hi @27pchrisl 

Using subclass works perfectly.

Thanks!
