### ISSUE TITLE
PostgreSQLSchemaManager doesn't find views columns

### ISSUE THREAD

**Issue by nepigu** [flat3/lodata#319]
Hi,

The project i'm working on is using lodata for our postgres views, and it seems like it stoped working some time ago. 
I went through the code to see what changed from our side, and it seems that the only thing that changed was that we've updated lodata to newer version.

After investigating why it is not working i've noticed that PostgreSQLSchemaManager -> selectTableColumns method is trying to find columns of provided table name, but because it's not a table, but a view - it doesn't find them.

Are you willing to add this functionality back ? 

The query that's been built when trying to find columns data:
`SELECT            a.attnum,
                  quote_ident(a.attname) AS field,
                  t.typname AS type,
                  format_type(a.atttypid, a.atttypmod) AS complete_type,
                  (SELECT tc.collcollate FROM pg_catalog.pg_collation tc WHERE tc.oid = a.attcollation) AS collation,
                  (SELECT t1.typname FROM pg_catalog.pg_type t1 WHERE t1.oid = t.typbasetype) AS domain_type,
                  (SELECT format_type(t2.typbasetype, t2.typtypmod) FROM
                      pg_catalog.pg_type t2 WHERE t2.typtype = 'd' AND t2.oid = a.atttypid) AS domain_complete_type,
                  a.attnotnull AS isnotnull,
                  (SELECT 't'
                   FROM pg_index
                   WHERE c.oid = pg_index.indrelid
                     AND pg_index.indkey[0] = a.attnum
                     AND pg_index.indisprimary = 't'
                  ) AS pri,
                  (SELECT pg_get_expr(adbin, adrelid)
                   FROM pg_attrdef
                   WHERE c.oid = pg_attrdef.adrelid
                     AND pg_attrdef.adnum=a.attnum
                  ) AS default,
                  (SELECT pg_description.description
                   FROM pg_description WHERE pg_description.objoid = c.oid AND a.attnum = pg_description.objsubid
                  ) AS comment
FROM pg_attribute a, pg_class c, pg_type t, pg_namespace n WHERE a.attnum > 0 AND a.attrelid = c.oid AND a.atttypid = t.oid AND n.oid = c.relnamespace AND c.relkind = 'r' AND c.relname = 'users_view' AND n.nspname = ANY(current_schemas(false)) AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') ORDER BY a.attnum
`

**Comment by 27pchrisl** [comment]
Hi @nepigu, yes views are supposed to work. Do you get a discovery error, or just an entity set that doesn't appear to have any properties?

**Comment by nepigu** [comment]
Hi @27pchrisl, no, i don't get an error, but entity set has the only property which i set manually - id.  Please see screenshots attached with both working and not working examples. 

Not working, view: 
<img width="538" alt="Screenshot 2022-09-15 at 18 12 31" src="https://user-images.githubusercontent.com/20725142/190442222-5bc4b3a9-3f35-46bf-969d-aa26381051ae.png">

Working, table:
<img width="491" alt="Screenshot 2022-09-15 at 18 11 43" src="https://user-images.githubusercontent.com/20725142/190442307-0bf41941-374e-412e-ae2a-a0823ac1b299.png">

**Comment by 27pchrisl** [comment]
Another Q (I'm trying to create a breaking test case) - are you using discovery via an Eloquent model, or using SQLEntitySet directly? Could you provide the code that creates the set? Thanks!

**Comment by nepigu** [comment]
I'm using SQLEntitySet, as views do not have eloquent models. Heres the code: 

> $entityType = new EntityType('view_name');
            $entityType->addDeclaredProperty('id', Type::string());
            $entityType->setKey($entityType->getProperty('id'));

> $set = (new SQLEntitySet('view_name', $entityType))
                ->setTable('view_name')
                ->discoverProperties();
            Lodata::add($set);

**Comment by 27pchrisl** [comment]
Hi, I need some more information about how the view is created.

If I create a really simple table named `passengers` with `id` and `name` columns, and then define the view as:
`create view airview as (select id, name from passengers)`, then the "id" and "name" columns of the view are correctly identified.

Is there a simple reproduction you can send over? Thanks!

**Comment by nepigu** [comment]
Hi, I've tried your query to create a new view, and the result is the same - i'm still getting only ids as a response. 
<img width="636" alt="Screenshot 2022-09-21 at 09 35 36" src="https://user-images.githubusercontent.com/20725142/191431710-94b58723-9d17-402a-898c-259ff3a15644.png">
<img width="627" alt="Screenshot 2022-09-21 at 09 35 46" src="https://user-images.githubusercontent.com/20725142/191431737-40c51e30-298a-4156-9242-70a71bea9f75.png">

We're using lodata 5.18, laravel 9.23 and php 8.0.22

The views are created exactly the same as in your example

**Comment by 27pchrisl** [comment]
Hi, it turns out this is due to https://github.com/doctrine/dbal/issues/5671
Lodata depends on `doctrine/dbal:^3`, so this update to DBAL 3.4 has been pulled in and has the behaviour change you are experiencing.

Based on the info in that ticket it doesn't sound like the maintainers are going to bring back the old behaviour, so I suggest either locking the DBAL version in your app to ~3.3.0 or manually entering the types into the Lodata `EntityType`.
