### ISSUE TITLE
New column is not in response

### ISSUE THREAD

**Issue by ChesterValentine** [flat3/lodata#424]
Hi,

I'm on 5.18 release.
I have some issue. I add a new column in a table.
I add it in the `$fillable` in the model.

The model is discover but in the API response, I didn't recover this property.

I clear all caches and I still don't have this new fillable property.

Can you help me to solve this issue?

Best regards,

ChesterValentine

**Comment by 27pchrisl** [comment]
Hi @ChesterValentine, you mentioned the model is discovered, does the column does appear in the metadata for the entity type? (`http://127.0.0.1:8000/odata/$metadata`)

Does the column have an unusual name, contain non-ascii characters, or has a type that isn't supported?

**Comment by 27pchrisl** [comment]
Hi @ChesterValentine, you mentioned the model is discovered, does the column does appear in the metadata for the entity type? (`http://127.0.0.1:8000/odata/$metadata`)

Does the column have an unusual name, contain non-ascii characters, or has a type that isn't supported?

**Comment by ChesterValentine** [comment]
Hi and thanks for your response.

I didn't see property in `http://127.0.0.1:8000/odata/$metadata`

The name of my column (in database and in the model) is `sort_on_site` . In the database, the type of the column is json. I cast the type of this column to array in the model like this : 
`protected $casts = [
        'sort_on_site' => 'array',
    ];`

**Comment by 27pchrisl** [comment]
One reason it might be ignored is if it exists in the `$hidden` or doesn't exist in the `$visible` properties of the model (if you're using those properties). Do you have other `json` properties that are working?

Also in your description you said the column was `sort_in_site` and the cast has `sort_on_site` - is one of those a typo?

**Comment by ChesterValentine** [comment]
Oh sorry, column and cast have the same name `sort_on_site` (I will edit my post, sorry).

Yes, I have other json properties, cast in array, that are working. And I didn't use `$hidden` and `$visible` properties in my model.

**Comment by 27pchrisl** [comment]
I can't immediately see what could cause this, are you able to provide a minimal migration and model that has this behaviour, so I can try and reproduce the issue in the test suite?

**Comment by ChesterValentine** [comment]
I saw where is my issue.
In my ODataServiceProvider boot method, I have a bug but I didn't saw it in the logs before I do this issue. It is a declared property that doesn't have a correct type which give me an error.

Sorry to take your time for this, our exhanges allowed me to discover that there are several errors in my ServiceProvider that I have to correct.

Thank you for your speed of response and this really great package.

Best regards,

ChesterValentine

**Comment by 27pchrisl** [comment]
No problem, glad you got it sorted!

**Comment by accexs** [comment]
hi @ChesterValentine  i was wondering if you may share your experience with json database columns, i have issues generating complex filters or for example to set a property inside the json as searchable
