### ISSUE TITLE
Power BI ERROR

### ISSUE THREAD

**Issue by tolgatasci** [flat3/lodata#441]
ERROR 

Details: "OData: The feed's metadata document appears to be invalid. Error: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/xml' matches the content type 'application/json'."

**Comment by 27pchrisl** [comment]
Hi @tolgatasci, I wasn't able to immediately reproduce this issue. Are you using `http://localhost:8000/odata` or similar as the feed URL for PowerBI ?

**Comment by tolgatasci** [comment]
![image](https://user-images.githubusercontent.com/9893685/212644987-8d6ce7d3-935c-470c-8ffd-d42b6698e266.png)

it like this

**Comment by 27pchrisl** [comment]
Something appears to be intercepting how the `Accept` header is being used. No matter what header I use, http://mercedes.remondis-tr.com/odata/$metadata always returns `application/json`. Is something in the server configuration forcing the `Accept` header to be `application/json` ?

**Comment by tolgatasci** [comment]
it really was. My fault, thanks.
