### ISSUE TITLE
The server has returned a non-numeric value in a response to an item count request

### ISSUE THREAD

**Issue by crisleiria** [flat3/lodata#460]
Hi all,

With default configurations I am getting this error from devexpress datagrid component:
`E4018 - The server has returned a non-numeric value in a response to an item count request. See: http://js.devexpress.com/error/22_2/E4018`

Datagrid is making this request: `xxx/odata/Users?%24top=10&%24count=true`
It returns data, I guess it should only return the number of records.

From Odata spec docs, this option exists (11.2.5.5):
[http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html](url)

Steps to reproduce:

latest Laravel 9 version
latest version of data grid devextreme 22.2
latest version of flat3/lodata (5.21) 

For testing purpose, I have connected to the already existing User Model Class from Laravel.

I follow the getting started docs, with no specific settings, it works out of the box.

this is my data grid oData store configuration from devextream:

`dataSource : {
        store : {
            type : 'odata',
            url : '/odata/Users',
            key: 'id',
            version : 4
        },
    }`

Everything else, is straightforward settings from devextream datagrid. Here is an example for odata:
[https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/OdataService/Vue/Light/](url)

**Comment by 27pchrisl** [comment]
@crisleiria Looks like DevExtreme supports OData 4.0, but not 4.01 (which is Lodata's default).

In 4.0 OData responses included control properties namespaced with `odata.` like `@odata.count`. Version 4.01 removed the `odata.`, so DE can't find what it's looking for.

However, you can downgrade Lodata's version to 4.0 and get the response you want by setting the `OData-Version` HTTP header to "4.0":

```js
export default {
  components: {
    DxDataGrid,
    DxColumn,
  },
  data() {
    return {
      dataSource: {
        store: {
          type: 'odata',
          url: 'http://localhost:8000/odata/Users',
          beforeSend: function (e) {  
            e.headers = {
              "OData-Version": "4.0"
            };
          }
          key: 'id',
          version: 4
        },
        select: [
          'id'
        ]
      },
    };
  },
};

```

**Comment by 27pchrisl** [comment]
Added to the [documentation](https://lodata.io/clients/devextreme.html)

**Comment by crisleiria** [comment]
@27pchrisl 

Thank for the reply, tomorrow I will try your suggestion, and let you know.

**Comment by crisleiria** [comment]
Yes, it works properly. Thank you @27pchrisl, I will close the issue.
