### ISSUE TITLE
Overriding pagination behavior

### ISSUE THREAD

**Issue by cladelpino** [flat3/lodata#479]
I've noticed that lodata changes pagination, sometimes returning a skip lower than the top when the resource has been queried many times.

Is there any way to override this behavior and force the server to return a skip that exactly matches top ?

Thanks!

**Comment by 27pchrisl** [comment]
Hi @cladelpino, there's not a direct way of overriding this, but you could create a subclass of the entity set class you're using, and override `getSkip()` to return a `Skip` object with its value set to the same thing as `getTop` returns.

Although this does sound like it might be a bug - is there an unusual condition in your application that might be causing this? After how many pages does this occur?

**Comment by cladelpino** [comment]
Thanks, do you have any example for that ? I couldn't find the section of the code handling skip and such at EntitySet or EloquentEntitySet to have as an example.

Looking into it, yes, it seems to be a bug, or at least it does generate incorrect behavior. Here I attach a log file of a set of requests made with top=5000 on a table with 444571 records with continuous ids. Behavior is:

* First call returns OK, ids 1 - top.
* Second call, and all successive, return records from skip+1 to skip+1000 and then batches of 1000 records spaced according to a series of weird jumps.
* The number of this "extra batches" decreases over time, leading to a diminishing effective page size. nextLink increases offset by this effective page size.

Consequences are some records are missing and some end up being requested more than once:

* If a record is not transmitted in one of the jumping batches, and is not in the first 1000 records from the skip of a call, it will be missing from the whole table download (there will never be a nextLink leading to it). In the example attached, records 6001-9999 are missing.
* If a record is transmitted in one of the jumping batches, and it is again in the first 1000 records from the skip of a call, it will appear many times in the download. In the example attached, record 345021 appears twice.

[pagination_test.log](https://github.com/flat3/lodata/files/10722726/pagination_test.log)

**Comment by 27pchrisl** [comment]
Okay this is happening because Lodata combines `lazyById` together with pagination, which is causing problems when the total number of records (including paginated) returned exceeds 5000.

Since using `$skip` isn't compatible with `lazyById`, I have updated the Eloquent entity set to use OData's `$skiptoken` parameter instead. As long as you're always following the `@nextLink` this will work fine.

Could you `composer require flat3/lodata:dev-gh-479` and let me know if the issue is resolved?

**Comment by cladelpino** [comment]
Yes, it has apparently been solved, although I will test it thoroughly in a few days. Thank you very much !!

**Comment by 27pchrisl** [comment]
I've pushed a different change. Based on a variety of tests, the ability for the caller to send arbitrary `$orderby` arguments is too complex to reconcile with `lazyById`. I have changed the `EloquentEntitySet` to use the `cursor` method instead, which is the same method the `SQLEntitySet` uses and it doesn't suffer from this issue. As all the tests are passing I'm going to release this change now.

**Comment by cladelpino** [comment]
Great work! Thanks
