### ISSUE TITLE
$select inside $expand only respects single attribute

### ISSUE THREAD

**Issue by Remo** [flat3/lodata#48]
I'm just posting this as I play around with lodata, there's no real use case for now, but before I start delving into the code and attempt to fix things on my own I'd like to know if lodata could work for us. For now just issues if you don't mind.

I've got two models in my demo project:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{   
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_name',
        'price',
    ];

    public function descriptions()
    {
        return $this->hasMany(ProductDescription::class);
    }

}
```

and 
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductDescription extends Model
{   
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_id',
        'language',
        'description',
    ];

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}
```

I expose it using this:
```php
\Lodata::discoverEloquentModel(\App\Models\ProductDescription::class);
\Lodata::discoverEloquentModel(\App\Models\Product::class)->discoverRelationship('descriptions');
```

I wanted to fetch a single product with all the descriptions. It works fine using this `/odata/Products(id=1)?$select=id,product_name&$expand=descriptions`, but I thought the `product_id` inside the descriptions array is superfluous and tried to remove it using this `/odata/Products(id=1)?$select=id,product_name&$expand=descriptions($select=language,description)`

The result of this is:

```
{
   "@context":"http://localhost:2015/odata/$metadata#Products(id,product_name,descriptions(language))/$entity",
   "id":1,
   "product_name":"Mickey",
   "descriptions":[
      {
         "language":"de"
      },
      {
         "language":"en"
      }
   ]
}
```

The description is missing. No matter what attribute I define, it only seems to include the first one.

**Comment by 27pchrisl** [comment]
Ok, this was a protocol implementation error - $expand query string elements should have been split by semicolons, not commas. So your $select was internally being converted to `['$select=language','description']` instead of `['$select=language,description']`

**Comment by Remo** [comment]
Awesome, that fixed it!
