### ISSUE TITLE
Add support `name`, `description`, `nullable` in `discoverRelationship` and `LodataRelationship` as in `LodataProperty`

### ISSUE THREAD

**Issue by RuslanMelnychenko** [flat3/lodata#502]
Hello. It would be great to add the ability to specify a custom field `name`, `description`, and `nullable` in `discoverRelationship` and `LodataRelationship`. To work as `LodataProperty`.

**Comment by 27pchrisl** [comment]
Yup, good call! Implemented in [v5.27.0](https://github.com/flat3/lodata/releases/tag/v5.27.0)

**Comment by RuslanMelnychenko** [comment]
Thanks so much!
