### ISSUE TITLE
Is possible to use $format=xml for Models?

### ISSUE THREAD

**Issue by RrOoSsSsOo** [flat3/lodata#508]
Is possible to use (and how) $format=xml for retreving Models in XML format? (and not only with $metadata)

I.e. [http://127.0.0.1:8000/odata/Users?$format=xml](http://127.0.0.1:8000/odata/Users?$format=xml))

```json
{
    "error": {
        "code": "unsupported_accept",
        "message": "This route does not support the accepted type, unsupported parameters may have been supplied",
        "target": null,
        "details": [],
        "innererror": {}
    }
}
```

**Comment by 27pchrisl** [comment]
Hi @RrOoSsSsOo, no that's not possible with Lodata. OData 3 used XML, but OData 4 has completely switched to using JSON for data payloads.
