### ISSUE TITLE
"missing_model_key"

### ISSUE THREAD

**Issue by thinkerytim** [flat3/lodata#526]
I have a SQL Server DB that uses GUIDs for all primary keys. It's sort of non-standard for the Laravel way of doing things but so far it's worked fine.

I defined my base model like this:

```
class BaseModel extends Authenticatable
{
    use HasFactory, HasUuids;

    /**
     * Non-standard ID column name
     */
    protected $primaryKey = 'ID';

    /**
     * Use sql server audit fields
     */
    const CREATED_AT = 'CreatedOn';
    const UPDATED_AT = 'ModifiedOn';
}
```

Then each of my child models can basically use this with no changes:

```
namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

class Geofence extends BaseModel
{

}
```

However, for some reason there's three tables / models that don't work and when I enable them in the `AppServiceProvider` using `\Lodata::discover(\App\Models\ProblemClass::class);` I get an error when accessing the OData endpoints:

`{"error":{"code":"missing_model_key","message":"The model App\\Models\\ProblemClass had no primary key","target":null,"details":[],"innererror":{}}}`

As far as I can see the table's definition (at least as far as regards the PK) is identical to all the others, so I'm not sure where to look to resolve this.

**Comment by 27pchrisl** [comment]
Hi @thinkerytim. So the way this works is that Lodata uses DBAL to ask for the table's indexes, then iterates over them to find the one DBAL considers the primary index, then reads the columns and tries to find a column that matches (case sensitively) the name of the first column in that primary index (Lodata does not support compound primary keys, but it doesn't sound like you use those).

Based on some quick searching, it looks like SQL Server might have case-insensitive, but possibly case-preserving column/index names, and that might additionally be affected by table collation. Does that sound possible in your configuration?

You could try modifying `src/Drivers/SQL/SQLSchema.php:62` to:
```php
return strcasecmp($column->getName(), $index->getColumns()[0]) === 0;
```

If that doesn't solve it, could you provide the SQL CREATE statement for the problematic table, to include the ID and index defintions?

**Comment by thinkerytim** [comment]
Thanks as always for the prompt help @27pchrisl -- I tried the modification you suggested, but it didn't resolve the problem.

Here's the create for a table that does NOT work:

```
create table dbo.KeywordLists
(
    ID          uniqueidentifier not null
        constraint PK_KeywordLists
            primary key,
    Name        nvarchar(max),
    Description nvarchar(max),
    Language    int              not null,
    Keywords    nvarchar(max),
    KeyValues   nvarchar(max),
    CreatedBy   nvarchar(128),
    CreatedOn   datetimeoffset   not null,
    ModifiedBy  nvarchar(128),
    ModifiedOn  datetimeoffset   not null
)
```

And here's one that DOES work:

```
create table dbo.GeoFences
(
    ID           uniqueidentifier not null
        constraint PK_GeoFences
            primary key,
    GeoFenceType int              not null,
    Name         nvarchar(max),
    Description  nvarchar(max),
    ULLat        float            not null,
    ULLon        float            not null,
    URLat        float            not null,
    URLon        float            not null,
    LRLat        float            not null,
    LRLon        float            not null,
    LLLat        float            not null,
    LLLon        float            not null,
    LineColor    nvarchar(max),
    KeyValues    nvarchar(max),
    CreatedBy    nvarchar(128),
    CreatedOn    datetimeoffset   not null,
    ModifiedBy   nvarchar(128),
    ModifiedOn   datetimeoffset   not null
)
go
```

I can't think of why one would work and the other would not.

**Comment by 27pchrisl** [comment]
@thinkerytim  It might be Laravel's conversion from CamelCase to snake_case. I added `protected $table = 'KeywordLists';` to override Laravel converting KeywordLists to keyword_lists, does that help?

**Comment by thinkerytim** [comment]
YES! that's it. Thank you so much! Your support is amazing-- really appreciate it.
