### ISSUE TITLE
Could please give me a example how to get data from laravel controller by using route ?

### ISSUE THREAD

**Issue by alif989** [flat3/lodata#530]
When I bind data in appServiceProvider then get data but when using laravel controller by using route then I can't anything. I have also configured by your documentation. 
Please give us for your valuable suggestion.  

![app_service_proverder](https://user-images.githubusercontent.com/36722507/225540654-5f53a242-a72b-4f8c-bcfe-eff27f03a2b2.png)
![call_using_route](https://user-images.githubusercontent.com/36722507/225540664-c5f11008-b754-4efa-8229-f9189093baba.png)
![controller_](https://user-images.githubusercontent.com/36722507/225540669-e22d4c78-3b9e-461c-957d-2cac9cb6ffb7.png)
![route_service_provider](https://user-images.githubusercontent.com/36722507/225540674-e69052d7-520f-43a5-aebe-e4286b22b386.png)

**Comment by 27pchrisl** [comment]
Hi, I can't see how the `UserController` is set up, but I assume it's forwarding that request to something like `/lodata/public/odata/import_v_emissions_calc` ?
