### ISSUE TITLE
Search syntax

### ISSUE THREAD

**Issue by thinkerytim** [flat3/lodata#531]
I'm using [Syncfusion's react components](https://ej2.syncfusion.com/react/documentation/grid/getting-started), and their grid works pretty well with the lodata endpoints out of the box. However, the search functionality is not working. 

The endpoint returns `SyntaxError: JSON.parse: unexpected character at line 1 column 69 of the JSON data`

This is the search query they send to the endpoint, when I designated `RoleName` and `Description` as searchable fields in the Syncfusion Grid options and search on the string `test`. 

```
http://localhost/odata/Roles/?$count=true&$filter=(contains(tolower(cast(RoleName,%20%27Edm.String%27)),%27test%27))%20or%20(contains(tolower(cast(Description,%20%27Edm.String%27)),%27test%27))&$skip=0&$top=12
```

These column are also designated as searchable in the `AppServiceProvider`:

```
\Lodata::discover(\App\Models\Role::class);
        \Lodata::getEntityType('Role')->getProperty('RoleName')->setSearchable();
        \Lodata::getEntityType('Role')->getProperty('Description')->setSearchable();
```

I've verified that the `Role` endpoint returns data using the normal `$search` format: 

`http://localhost/odata/Roles?$search=Role`

**Comment by 27pchrisl** [comment]
Hi @thinkerytim, this was due to the lack of support for the `cast` function. I have added support for this in [v5.28.0](https://github.com/flat3/lodata/releases/tag/v5.28.0).

**Comment by thinkerytim** [comment]
Hmm-- upgraded to 5.29 and no change.

**Comment by 27pchrisl** [comment]
Could you capture the full request and response coming back from Lodata to the browser?

**Comment by thinkerytim** [comment]
I'm sorry Chris, this was my fault. Syncfusion doesn't know what the underlying data types are, and so it was sending a string search against (for example) a boolean field. When I restricted the search to use only string data type columns, it works as expected. Thank you!

**Comment by 27pchrisl** [comment]
Makes sense!
