### ISSUE TITLE
indexof in $filter not zero based when using MySQL as database

### ISSUE THREAD

**Issue by unidoct** [flat3/lodata#557]
When I am using indexof in a $filter it seems to not be zero based when using MySQL as database. From the code I could see, that indexof is mapped to the mysql INSTR function which also isn't zero based. Is this intentional or is this a bug? Since the spec says that indexof should be zero based.

**Comment by 27pchrisl** [comment]
It was a bug, thanks for the report! Fixed in [v5.32.0](https://github.com/flat3/lodata/releases/tag/v5.32.0)

**Comment by unidoct** [comment]
Thanks for the quick fix!
