### ISSUE TITLE
Support `StringBackedEnum`

### ISSUE THREAD

**Issue by RuslanMelnychenko** [flat3/lodata#572]
Hello. My Laravel Eloquent Model has attribute type by `BackedEnum`, but string type.
Is it possible to implement `StringBackedEnum` support in the future?
I've now implemented `StringBackedEnum` support with `GeneratedProperty`, but it's kind of a workaround

**Comment by 27pchrisl** [comment]
I don't think this is something the library itself can support, as the OData specification only allows for integer backed enums. But it's good that there is a workaround 👍

**Comment by erycson** [comment]
Create `LodataServiceProvider.php` file and try this:


```php
<?php

namespace App\Providers;

use Doctrine\DBAL\Types\StringType;
use Doctrine\DBAL\Types\Type;
use Illuminate\Support\Facades\DB;

class LodataServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        // It's worked for me
        if (!Type::hasType('enum')) {
            Type::addType('enum', StringType::class);
        }

        DB::getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Eloquent with Enum field
        Lodata::discover(User::class);
    }
}

```

**Comment by underdpt** [comment]
Hi @RuslanMelnychenko 

How did you implement support for `StringBackedEnum`? Do you have any example? I'm hitting a wall here...

Thanks!
