### ISSUE TITLE
oracle oci8 driver | invalid_driver error

### ISSUE THREAD

**Issue by gertaMng** [flat3/lodata#594]
Hello,

I'm currently using lodata on a laravel project with a connection with oracle DB:
- Laravel 10
- Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit
- PDO driver: https://github.com/yajra/laravel-oci8
- Lodata v.5.32.0

While making the request
GET http://localhost:8000/odata/Division?$orderby=label asc
Lodata responds with 200 OK and I get the following error as a response:
```
{
    "@context": "http://localhost/odata/$metadata#divisions",
    "value": [
        OData-error: {
            "code": "invalid_driver",
            "message": "An invalid driver was used",
            "target": null,
            "details": [],
            "innererror": {}
        }
```

The database configuration is as follows:

```
'oracle_migration' => [
            'driver' => 'oracle',
            'tns'            => env('MIGRATION_DB_TNS', ''),
            'host'           => env('MIGRATION_DB_HOST', ''),
            'port'           => env('MIGRATION_DB_PORT', '1521'),
            'database'       => env('MIGRATION_DB_DATABASE', ''),
            'service_name'   => env('MIGRATION_DB_SERVICE_NAME', ''),
            'username'       => env('MIGRATION_DB_USERNAME', ''),
            'password'       => env('MIGRATION_DB_PASSWORD', ''),
            'charset'        => env('MIGRATION_DB_CHARSET', 'AL32UTF8'),
            'prefix'         => env('MIGRATION_DB_PREFIX', ''),
            'prefix_schema'  => env('MIGRATION_DB_SCHEMA_PREFIX', ''),
            'edition'        => env('MIGRATION_DB_EDITION', 'ora$base'),
            'server_version' => env('MIGRATION_DB_SERVER_VERSION', '12g'),
            'load_balance'   => env('MIGRATION_DB_LOAD_BALANCE', 'yes'),
            'dynamic'        => [],
]
```

The Division Model:

```
#[
    LodataIdentifier('divisions'),
    LodataTypeIdentifier('division'),
    LodataInt64(
        name: 'id',
        key: true
    ),
    LodataString(
        name: 'code',searchable: true
    ),
    LodataString(name: 'label',searchable: true),
    LodataString(name: 'email',searchable: true),
]
class Division extends Model
{
    /**
     * @var string $primaryKey
     */
    protected $primaryKey = 'id';

    protected $fillable = [
        'code',
        'label',
        'email'
    ];

    protected $casts = [
        'ID' => 'integer',
        'CODE' => 'string',
        'LABEL' => 'string',
        'EMAIL' => 'string'
    ];
}
```

The discovery of Division model in LodataServiceProvider:

`Lodata::discover(\App\Models\Division::class);`

I see that on _SQLConnection.php_ inside the method _quoteSingleIdentifier()_, **oci8** drive case is no handled.

Is there any way to handle drivers different from the ones listed on _SQLConnection.php_ ?

**Comment by 27pchrisl** [comment]
The way to get this functionality running would be to extend `EloquentEntitySet` and then override `quoteSingleIdentifier()`. Once you've done that, instead of:

`Lodata::discover(\App\Models\Division::class);`

use

`(new OracleEloquentEntitySet(\App\Models\Division::class))->discover()`

I think if you did that then the basic entity set functionality such as pagination has a good chance of working.

However, if you wanted to be able to use `$filter` and `$search` and other advanced functionality, you would have to implement Oracle-specific syntax in `Flat3\Lodata\Drivers\SQL\SQLExpression`, which is more complex.

Let me know if simply adding the case for `OraclePlatform` works and I will add it to the package.

**Comment by gertaMng** [comment]
Hi @27pchrisl it works following your instructions,
by extending EloquentEntitySet and handling OraclePlatform case as follows:

```
class OracleEloquentEntitySet extends EloquentEntitySet
{

    /**
     * Modify identifier quote types by driver
     * @param  string  $identifier  String to quote
     * @return string Quoted identifier
     */
    public function quoteSingleIdentifier(string $identifier): string
    {
        $driver = new OraclePlatform();
        return $driver->quoteSingleIdentifier(mb_strtoupper($identifier));
    }
}
```

**Comment by 27pchrisl** [comment]
Great!
