### ISSUE TITLE
setBoundParameter doesn't support string

### ISSUE THREAD

**Issue by Remo** [flat3/lodata#70]
In the readme we've got examples like this:

```php
Lodata::add((new class('identity') extends Operation implements FunctionInterface {
    public function invoke(String_ $code): String_
    {
      return $code;
    }
})->setBoundParameter('code');
```

But this doesn't work for me, the parameter `PipeInterface` or `null`:
https://github.com/flat3/lodata/blob/f7c2760d1c7e532b6d995284cc6b1ecb5158b14d/src/Operation.php#L224-L239

**Comment by 27pchrisl** [comment]
Ah apologies that's another documentation glitch, the example is wrong and the method should be `setBindingParameterName`.

**Comment by 27pchrisl** [comment]
Fixed the documentation issue in https://github.com/flat3/lodata/commit/b16352927c1999f490645ffa99af679546164d73
