### ISSUE TITLE
Using nested json objects for filters, set json casts properties as searchable

### ISSUE THREAD

**Issue by accexs** [flat3/lodata#706]
Hello,

lets say i have the following entity
```
{
  "name": "Myname",
  "lastName": "Lastname",
  "properties": {
    "one": 1,
    "two": 2,
    "info": "someinfo"
  }
}
```

`$properties` is a json column casted on my model and i manage to make it searchable (works for all attributes, meaning "one", "two" and "info") are part of the match options for `search`

What am not able to do is create a complex filter for example:

`?filter=contain(properties/info, 'som')`

Also it would be nice to be able to set nested properties as searchable right now am doing something like this which works for the whole object:

`->getProperty('properties')->setSearchable();`

But i was wondering if i could make just "info" searchable

**Comment by 27pchrisl** [comment]
Hi @accexs, currently Lodata doesn't have support for this type of operation. Probably the expression parser does understand the syntax, but there's no method in `src/Drivers/SQL/SQLExpression.php` to convert the navigation property to an SQL expression. If you wanted to try writing the functionality then the `lambdaExpression` function might be a good place to look as it works with navigation properties as well.

**Comment by accexs** [comment]
Thanks @27pchrisl , what i did was to create a generated column on my table. That way i can handle my edge case.
