### ISSUE TITLE
Parsing $batch POST body fails when connecting via openui5 app

### ISSUE THREAD

**Issue by mgerzabek** [flat3/lodata#775]
First of all, thanks for the awesome package!

When connecting to loadata via openui5 a typical $batch request looks like
```request
--batch_id-1705220807755-21
Content-Type:application/http
Content-Transfer-Encoding:binary

GET Times?$skip=0&$top=500 HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:de-DE
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true


--batch_id-1705220807755-21--
Group ID: $auto
```

The parsing in class `Flat3\Lodata\Transaction\MultipartDocument->parseDocuments()` fails in line 124 where it assumes that the header atttributes for each individual request is split by `: ` (colon + space) but in the given request it's only `:` without space. The explode fails with an `\ErrorException: Undefined array key 1`.

As I didn't need to care about oData specs before, I'm wondering if the split has to be colon + space or if it is rather unspecified how the header attributes in $batch requests are formated.

Can I move on and fix the respective class within a PR? Do I need to know something about that?
Any hints welcome.

**Comment by 27pchrisl** [comment]
Hi @mgerzabek, it is a spec error, but from the [http spec](https://www.rfc-editor.org/rfc/rfc2616#section-4.2). There is optional white space around the header value that should be removed. If you do a PR to split on the first colon, and then white space trim the value I think that’ll work for both cases and I’ll merge and release a patch.

**Comment by 27pchrisl** [comment]
Fixed in https://github.com/flat3/lodata/releases/tag/v5.32.4

**Comment by mgerzabek** [comment]
Awesome! Thank you.
