### ISSUE TITLE
Add filters in code (SQLEntitySet)

### ISSUE THREAD

**Issue by yannickdesmadryl** [flat3/lodata#785]
I created a view with data for all users. 
This is an SQL Entity Set. There is no 'getBuilder' functionality like the Eloquent Entity Set.

How can I hook in the filters, dynamically? 

The query should be: 'select * from files_view where user_id = ?'
Where statement is not applied via url but in code.

How can I achieve that? 

Thanks,
Yannick

**Comment by 27pchrisl** [comment]
Hi @yannickdesmadryl, I think the best place would be to override `generateWhere()`. Maybe something along these lines:

```php
protected function generateWhere(): SQLExpression
{
  $expression = parent::generateWhere(); // Use the parameters provided in the URL

  if ($expression->hasStatement()) {
    $expression->pushStatement('AND');
  }

  $expression->pushStatement('user_id = ?');
  $expression->pushParameter(4);

  return $expression;
}
```

**Comment by yannickdesmadryl** [comment]
> Hi @yannickdesmadryl, I think the best place would be to override `generateWhere()`. Maybe something along these lines:
> 
> ```
> protected function generateWhere(): SQLExpression
> {
>   $expression = parent::generateWhere(); // Use the parameters provided in the URL
> 
>   if ($expression->hasStatement()) {
>     $expression->pushStatement('AND');
>   }
> 
>   $expression->pushStatement('user_id = ?');
>   $expression->pushParameter(4);
> 
>   return $expression;
> }
> ```

Thanks
