### ISSUE TITLE
$batch URL is set to http:// instead of the original https://

### ISSUE THREAD

**Issue by alexamart** [flat3/lodata#787]
Hello again, 

I'm not sure if this issue belongs to the package itself or it could be Syncfusion's (which i'm integrating with) -  I'm a little lost on where to look at.

I'm succesfully using batch requests on development at localhost (without ssl).

While testing on production with ssl everything works just fine, only batch requests fail. It correctly loads the data that with:  

https://mydomain.com/odata/Docentes/?$count=true&$skip=0&$top=12

however batch POST is sent as:

http://mydomain.com/odata/$batch

Appreciate any help :)

**Comment by 27pchrisl** [comment]
Hi @alexamart, if Syncfusion is following URLs from previous responses to build new ones, then URLs might have non-http links if Laravel is not set up for trusted proxies as in https://laravel.com/docs/10.x/requests#configuring-trusted-proxies. A quick way to check this would be to use https://laravel.com/docs/10.x/requests#trusting-all-proxies

**Comment by alexamart** [comment]
Thank you for the guidance, @27pchrisl
