### ISSUE TITLE
Is it possible to return EntitySet from Operation?

### ISSUE THREAD

**Issue by mgerzabek** [flat3/lodata#792]
I'm struggling in finding the right way to handle specialized query logic with Lodata. I have a big table with postings and want to do some distinct queries on that table combined with a filter. 

My first approach was to create a view to aggregate all related info on the database level. I created the EntityType for that view by hand. With that setup the filtering is done in Lodata, but the performance is suboptimal. Further I don't know how to express the distinct clause, which should go into the select statement itself.

My second approach was to do the distinct query in a Lodata function. This way I can grab the query parameter und do the specialized query in the database, but I fail when returing the Eloquent Collection.

The message from the system is `Flat3\\Lodata\\Operation::ensureResult(): Return value must be of type ?Flat3\\Lodata\\Interfaces\\PipeInterface, Illuminate\\Support\\Collection returned`.

Is it possible to return an `EntitySet` from a function? How would I do this?

**Comment by 27pchrisl** [comment]
Hi @mgerzabek,

If your code is doing the heavy lifting of creating the collection you should be able to achieve this by subclassing the `EnumerableEntitySet`, something like this:

```php
class ExampleEntitySet extends EnumerableEntitySet {
  public function query() {
    $this->enumerable = EloquentModel::where(<complex logic>)->get()->collect();

    return parent::query();
  }
}
```

Then in your service provider you can use this entity set with the entity type you defined yourself.

**Comment by mgerzabek** [comment]
Hi @27pchrisl,

Thank's again for your rapid response!

I followed your advice and created an `EnumerableEntitySet` like

```php
class DistinctUsers extends EnumerableEntitySet
{

    private function __construct() {
        parent::__construct('DistinctUsers', $this->getEntityType());
    }

    public function getEntityType(): EntityType
    {
        $entityType = new EntityType('DistinctUser');
        $entityType->setKey(new DeclaredProperty('id', Type::int64()));
        $entityType->addDeclaredProperty('name', Type::string());
        return $entityType;
    }

    public static function getEntitySet(): EntitySet {
        return new DistinctUsers();
    }

    public function query(): \Generator
    {
        // $date hard coded for rapid prototyping…
        $this->enumerable = $this->distinctUsersByDate('2022-01-10')->collect();
        return parent::query();
    }

    protected function distinctUsersByDate(string $date): Collection
    {
        return DB::table('postings_view')
            ->select('user_id', 'name')
            ->where('date', '=', $date)
            ->distinct()
            ->get();
    }
}
```

Unfortunately now I get the error `Flat3\Lodata\Drivers\EnumerableEntitySet::fillRecord(): Argument #1 ($item) must be of type array, App\Models\PostingView given`.

**Comment by 27pchrisl** [comment]
Hiya, you'll need to convert the Models to arrays. Maybe something like `collect($this->distinctUsersByDate('2022-01-10')->toArray());`

**Comment by mgerzabek** [comment]
Since I override the filtering anyways I ended up with

```php
foreach ($this->enumerable->all() as $item) {
    yield $this->toEntity(get_object_vars($item));
}
```

and did not call `parent::query()`. This leaves me with what I was looking for. 

To finally make it work, I also had to override the `count()` function.

```php
public function count(): int
{
    return $this->enumerable->count();
}
```

Thanks again for your help!
