### ISSUE TITLE
TINYINT in Model is wrongly converted to EDM.Boolean?

### ISSUE THREAD

**Issue by mgerzabek** [flat3/lodata#797]
Hey @27pchrisl,
 
I'm not sure if this is by intention or a defect. 

I have a couple of customizing tables that have a PK of TINYINT UNSIGNED AUTOINCREMENT. Those are referenced in different models via $table->unsignedTinyInt(…) in the migrations.

The `metadata.xml` says, those are of type `EDM.Boolean`, but in fact they are of type `EDM.Byte`.

As a workaround in my `AppServiceProvider` I explicitly rewire those attributes via

```php
Lodata::getEntitySet('…')
        ->getType()
        ->getProperty('ref_type_id')
        ->setType(Type::byte());
```

This way the relations of my model are kept in order. 

Can you please clarify the correct behaviour and classify this issue accordingly?

**Comment by 27pchrisl** [comment]
Hi @mgerzabek, is this a mysql database? This could be DBAL interpreting the tinyint column as a boolean: https://github.com/doctrine/dbal/blob/c70bae9e69e0e543044d5e282a624d9b3cbea6fb/src/Platforms/AbstractMySQLPlatform.php#L748
If that's the case then overriding the type in the way you have might be the only solution, as Lodata goes by what DBAL says the type is.

**Comment by mgerzabek** [comment]
Hi @27pchrisl, yes I'm using MySQL and thank you for clarifying!
As it's MySQL that has no native `boolean` data type, I will continue to rewire attributes in question like I already did.
Thank's again for the rapid response.
