### ISSUE TITLE
Doctrine\DBAL\Driver\PDO\Exception could not find driver

### ISSUE THREAD

**Issue by kristalis** [flat3/lodata#90]
Hi Chris, hope all is well.  I seem to have this error message when using the pkg.  I installed the app on a linux server and run composer update which comes up with the above error message. Can you  please advise as to the solution if you have encountered something similar
composer.json require

php : ^7.3 | ^8.0
doctrine/dbal:  ^2.1
flar3/lodata: 61.11
framework : ^8.4

**Comment by 27pchrisl** [comment]
@kristalis Hi I assume you resolved this? Could you say what the problem was? Thanks!

**Comment by kristalis** [comment]
Yes sorry, I enabled these in the php.ini and it worked
[PHP_PDO]
extension=php_pdo.dll
[PHP_PDO_MYSQL]
extension=php_pdo_mysql.dll
