### ISSUE TITLE
Odata Schema

### ISSUE THREAD

**Issue by kristalis** [flat3/lodata#91]
Hi Chris

How do I pull the schema to get the collections names and data types

regards
K

**Comment by 27pchrisl** [comment]
Hiya, OData supports getting the schema either as JSON or XML at this URL: `http://localhost:8000/odata/$metadata`. You must provide an `Accept` HTTP header to specify the format, either `application/json` or `application/xml`. For example this curl request:

```
curl -H 'Accept: application/xml' 'http://localhost:8000/odata/$metadata'
```

Will return the CSDL metadata in XML format `https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html`

**Comment by kristalis** [comment]
Thanks
