### ISSUE TITLE
lodata with existing CRUD API

### ISSUE THREAD

**Issue by ozgurunat** [flat3/lodata#96]
I have my CRUD APIs up and running but struggling to find the correct URI for odata end point.

odata/api/assets yields below message :

![image](https://user-images.githubusercontent.com/62070263/127168958-1bb26813-4d11-48e6-8294-bdc7f7abf17c.png)

I have my Assets GET route defined in api.php as :

Route::get('/assets', [AssetController::class, 'index']);

What should I do next ?

**Comment by 27pchrisl** [comment]
Hi, Lodata operates outside of Laravel’s routing system, so you should use the Lodata model instead.

There is new documentation here: https://lodata.io/getting-started/ which could be useful to get started, and then it sounds like you might be exposing media assets? In which case https://lodata.io/modelling/drivers/filesystem.html might be useful.

**Comment by ozgurunat** [comment]
I managed to return data through :

![image](https://user-images.githubusercontent.com/62070263/127173274-6c8e2024-8f16-4e51-9f80-c1e4df046c0d.png)

It turns out it is case sensitive and I have to type Assets with capital "A"

I will visit the documentation. Thanks.

**Comment by 27pchrisl** [comment]
Ah great! I'll update the documentation to make it clearer the URLs are case sensitive.
