### ISSUE TITLE
Error : The provided query had no properties marked searchable

### ISSUE THREAD

**Issue by ozgurunat** [flat3/lodata#97]
Hi Chris,

I receive below error message when I try to run "http://127.0.0.1:8000/odata/Assets?$search=ext"

![image](https://user-images.githubusercontent.com/62070263/127473359-60c4657d-c3d0-4ab3-b5dd-f41e50832690.png)

Any ideas what might be wrong here?

Thanks,
Ozgur

**Comment by 27pchrisl** [comment]
Hiya, this was another area that wasn't well documented, but I have created this page now that should help: https://lodata.io/modelling/search.html

Basically, you have to tell Lodata which properties are suitable for searching using a snippet like this, if you wanted to make Lodata's search look at the "description" property of your "Asset" type. You can make multiple properties searchable if you like.

```php
$assetType = Lodata::getEntityType('Asset');
$assetType->getProperty('description')->setSearchable();
```

**Comment by 27pchrisl** [comment]
Hiya, this was another area that wasn't well documented, but I have created this page now that should help: https://lodata.io/modelling/search.html

Basically, you have to tell Lodata which properties are suitable for searching using a snippet like this, if you wanted to make Lodata's search look at the "description" property of your "Asset" type. You can make multiple properties searchable if you like.

```php
$assetType = Lodata::getEntityType('Asset');
$assetType->getProperty('description')->setSearchable();
```
